# -------- Swiftlint --------
#
# Rule types: Lint, Idiomatic, Style, Metrics, Performance
#
# -------- Configuration --------

opt_in_rules:
# lint
 - accessibility_label_for_image
 - accessibility_trait_for_button
# - anyobject_protocol deprecated
 - array_init
 - balanced_xctest_lifecycle
 - discarded_notification_center_observer
 - empty_xctest_method
 - expiring_todo
 - ibinspectable_in_extension
 - identical_operands
 # - inert_defer deprecated
 - local_doc_comment
 - lower_acl_than_parent
 - nslocalizedstring_key
 - nslocalizedstring_require_bundle
 - overridden_super_call
 - override_in_extension
 - private_action
 - private_outlet
 - private_subject
 - prohibited_interface_builder
 - prohibited_super_call
 - quick_discouraged_call
 - quick_discouraged_focused_test
 - quick_discouraged_pending_test
 - raw_value_for_camel_cased_codable_enum
 - required_enum_case
 - strong_iboutlet
 - test_case_accessibility
 - unhandled_throwing_task
 - unowned_variable_capture
 # - unused_capture_list deprecated
 - weak_delegate
 - yoda_condition

# idiomatic
 - convenience_type
 - discouraged_assert
 - discouraged_none_name
 - discouraged_object_literal
 - discouraged_optional_boolean
 - discouraged_optional_collection
 - explicit_enum_raw_value
 - explicit_init
 - fallthrough
 - fatal_error_message
 - file_name_no_space
 - force_unwrapping
 - function_default_parameter_at_end
 - implicitly_unwrapped_optional
 - joined_default_parameter
 - legacy_multiple
 - legacy_objc_type
 - nimble_operator
 - no_extension_access_modifier
 - no_magic_numbers
 - object_literal
 - pattern_matching_keywords
 - prefer_zero_over_explicit_init
 - redundant_nil_coalescing
 - redundant_type_annotation
 - return_value_from_void_function
 - shorthand_optional_binding
 - static_operator
 - strict_fileprivate
 - toggle_bool
 - unavailable_function
 - untyped_error_in_catch
 - xct_specific_matcher

# metrics
 - closure_body_length
 - enum_case_associated_values_count

# performance
 - contains_over_filter_count
 - contains_over_filter_is_empty
 - contains_over_first_not_nil
 - contains_over_range_nil_comparison
 - empty_collection_literal
 - empty_count
 - empty_string
 - first_where
 - flatmap_over_map_reduce
 - last_where
 - reduce_into
 - sorted_first_last

# style
 - attributes
 - closure_end_indentation
 - closure_spacing
 - collection_alignment
 - comma_inheritance
 - direct_return
 - implicit_return
 - let_var_whitespace
 - literal_expression_end_indentation
 - modifier_order
 - multiline_arguments
 - multiline_arguments_brackets
 - multiline_function_chains
 - multiline_literal_brackets
 - multiline_parameters
 - multiline_parameters_brackets
 - number_separator
 - operator_usage_whitespace
 - optional_enum_case_matching
 - period_spacing
 - prefer_self_in_static_references
 - prefer_self_type_over_type_of_self
 - prefixed_toplevel_constant
 - redundant_self_in_closure
 - self_binding
 - single_test_class
 - sorted_enum_cases
 - sorted_imports
 - superfluous_else
 - trailing_closure
 - unneeded_parentheses_in_closure_argument
 - vertical_parameter_alignment_on_call
 - vertical_whitespace_closing_braces
 - vertical_whitespace_opening_braces


# opt-in rules that I want to keep disabled
# - anonymous_argument_in_multiline_closure
# - conditional_returns_on_newline
# - custom_rules
# - explicit_acl
# - explicit_top_level_acl
# - explicit_type_interface
# - extension_access_modifier
# - file_header
# - file_name
# - file_types_order   # (should try to connect after fix SwiftUI Preview false positive)
# - indentation_width
# - missing_docs
# - no_grouping_extension
# - required_deinit
# - switch_case_on_newline
# - type_contents_order
# - vertical_whitespace_between_cases


# disable rules that are enabled by default
disabled_rules:
- multiple_closures_with_trailing_closure


analyzer_rules:
 - capture_variable
 - explicit_self
 - unused_declaration
 - unused_import
 - typesafe_array_init

included: # paths to include during linting. `--path` is ignored if present.
  - ../Sources
  - ../Tests
  - ./

excluded:
  - docs
  - fastlane
  - .build
  - .swiftpm
  - Package.swift

closure_body_length:
  warning: 50
  error: 60

line_length:
  warning: 180
  error: 190

file_length:
  warning: 220
  error: 300

identifier_name:
  min_length:
    warning: 0
    error: 0
  excluded:
    - T
    - URL
    - ID
    - id

nesting:
  type_level:
    warning: 2
    error: 3


number_separator:
  minimum_length: 6

type_name:
  excluded:
    - T